### ISSUE TITLE
S3 object support?

### ISSUE THREAD

**Issue by lando-cal** [MrHertal/react-admin-amplify#11]
Does, or will, this support image/document/etc. upload and pull from S3, as Amplify does?
Thanks for the excellent work, by the way!

**Comment by MrHertal** [comment]
It would be a good feature indeed. I am considering adding that by the end of the year, around November.

**Comment by MrHertal** [comment]
This is now supported! here is the documentation: https://github.com/MrHertal/react-admin-amplify#storage
