### ISSUE TITLE
cognito keep return no current user

### ISSUE THREAD

**Issue by tommy921092** [MrHertal/react-admin-amplify#12]
I cloned your demo with amplify init --app 'the link', and after adding the cognito user groups in my aws cognito console, I failed to login and it keeps returns something like 'no current user', failed to get user pool etc...Do you know why it happens? Thanks.

**Comment by MrHertal** [comment]
You made me realize that cloning the demo to bootstrap a project is not easy.

I just updated the demo and added some instructions to do that : https://github.com/MrHertal/react-admin-amplify-demo#how-to-clone-this-project

Try to follow these steps and tell me if that worked.

**Comment by tommy921092** [comment]
Thanks, it works!
By the way, can you explain the use case for the user page?
I logged in and tried to create a user using superadmin account in the panel, but then the created account is not created in cognito, checking the code in User.js it seems this is not creating a cognito user. Instead it is just creating a user record in dynamodb, is it a left-to-do task?

**Comment by MrHertal** [comment]
Yes, you should not care about user and super admin group and you can remove it. I only made this to manage the demo user, who is the user publicly used by everyone to access the demo.

Managing Cognito users from the admin is something I want to add in a future release.

**Comment by umepon0626** [comment]
@MrHertal 
Thank you for your nice project!
I have same problem in my own react admin project.

I use Amplify/Auth and API, created cognito user group 'admin' and add some demo users to the group.
After that, I start dev server with `yarn start` and  login page keeps returning 'no current user' error with right userName and password.....

How can I fix the error?

```
function App() {
  return (
    <Admin
      authProvider={buildAuthProvider({ authGroups: ["admin"] })}
      dataProvider={buildDataProvider({ queries, mutations })}
    >
      <Resource name="items" create={ItemCreate} show={ItemShow} edit={ItemEdit} list={ItemList} options={{ authGroups: ["admin"] }}/>
    </Admin>
  );
}
```

**Comment by umepon0626** [comment]
enter the wrong username and password, it returns `user does not exist` correctly.

**Comment by umepon0626** [comment]
window.LOG_LEVEL = 'DEBUG';

and get 

<img width="360" alt="スクリーンショット 2021-02-18 12 26 59" src="https://user-images.githubusercontent.com/43326360/108301215-e0a00e00-71e4-11eb-9bdd-b3c3c06ac3b1.png">

**Comment by MrHertal** [comment]
Hi @umepon0626 

Can you show me the errors returned by Cognito (if there is) in the network tab of your dev tool ?

like this snapshot:

<img width="1670" alt="snap" src="https://user-images.githubusercontent.com/11944221/108327689-fe14ae00-71cb-11eb-8cff-a6f87005bd15.png">

**Comment by umepon0626** [comment]
@MrHertal Thank you for responding!!

Sorry, there are no error responses.....

<img width="1278" alt="スクリーンショット 2021-02-18 20 23 36" src="https://user-images.githubusercontent.com/43326360/108350147-31d0f180-7227-11eb-9d05-e97a0b4187c0.png">

**Comment by umepon0626** [comment]
<img width="1440" alt="スクリーンショット 2021-02-18 20 25 56" src="https://user-images.githubusercontent.com/43326360/108352523-5084b780-722a-11eb-8a9d-d39806cb4e57.png">

it is the console after I reload login screen

**Comment by tommy921092** [comment]
@umepon0626 As I remember this is something related to the cognito group, you may need to add the group first then add group to the user pool, the user may need to be verified. It's a bit tricky.

**Comment by umepon0626** [comment]
@tommy921092 Thank you for your comment!!
Yes, I know and I did it. (Sorry for my forgetting letting you know the situation detail...)

<img width="527" alt="スクリーンショット 2021-02-18 22 19 28" src="https://user-images.githubusercontent.com/43326360/108362662-6056c880-7237-11eb-8ae0-cdec29775e03.png">


<img width="1104" alt="スクリーンショット 2021-02-18 22 17 15" src="https://user-images.githubusercontent.com/43326360/108362430-1241c500-7237-11eb-8999-8e4d5f12c1a7.png">

**Comment by MrHertal** [comment]
Looks like your admin user must change is password before he can sign in

**Comment by MrHertal** [comment]
Check that link to set the password with the aws cli: https://stackoverflow.com/a/56948249/4140356

**Comment by umepon0626** [comment]
＠MrHertal
Thank you!!! I'll try it!

**Comment by umepon0626** [comment]
@MrHertal 
I did it and succeeded to login!

**Comment by umepon0626** [comment]
@MrHertal 
I succeeded to login with localhost and after published, I failed login with the same username and password....
Do you have any Idea or solution of this propblem?

<img width="1440" alt="スクリーンショット 2021-02-20 22 19 06" src="https://user-images.githubusercontent.com/43326360/108596658-c6735500-73c9-11eb-9eb8-e6e57941ebf9.png">

**Comment by MrHertal** [comment]
This is weird because you got the same challenge than before "PASSWORD_VERIFIER". I think it means that password must be set again...

**Comment by MrHertal** [comment]
Are you sure that your user "test" has a password definitely set?

**Comment by umepon0626** [comment]
@MrHertal 
Yes, I did the same process (make user in console and change password with command line via cli)
<img width="1045" alt="スクリーンショット 2021-02-21 9 40 22" src="https://user-images.githubusercontent.com/43326360/108612142-13d2df00-7429-11eb-92ed-04a83e854540.png">

**Comment by umepon0626** [comment]
@MrHertal  I deleted cloudfront cache and this problem solved....
