### ISSUE TITLE
How to limit user of a certain merchant group access to own resources?

### ISSUE THREAD

**Issue by tommy921092** [MrHertal/react-admin-amplify#13]
I just encountered another issue using the library.
My use case is to handle multi-merchant business - each user account (admin) belongs to a merchant group. 
How can I do something like listing only the records belong to each merchant user, which means a merchant cannot see other merchant's resources(such as transaction, employee info, user info etc?)

I have already integrated my cognito users signup with dynamoDB and also login info stored in redux, so now I can fetch user info, user groups and query dynamoDB to get the merchant group that user belong to. The problem is now with the query...any suggestion?

**Comment by MrHertal** [comment]
Have you checked dynamic group auth?

https://docs.amplify.aws/cli/graphql-transformer/directives#dynamic-group-authorization

**Comment by tommy921092** [comment]
That's exactly what I need, and it's working now, Thanks!
