### ISSUE TITLE
AWSS3Provider - ensure credentials error No Auth module registered in Amplify

### ISSUE THREAD

**Issue by mgiorgi-github** [MrHertal/react-admin-amplify#38]
I've follow the Storage implementation but when i select a file from AmplifyFileInput or AmplifyImageInput i see this error in console:
**AWSS3Provider - ensure credentials error No Auth module registered in Amplify
No credentials**
The storage is not public (require valid user) but i'm logged into react-admin with "Admin" user and i see all other data
How can i do?

**Comment by mgiorgi-github** [comment]
I've reinstall @aws-amplify/auth and now the image is loader... but when i save my form i've an error about "images" field name:
"The variables input contains a field name 'images' that is not defined for input object type 'CreatePillInput' " but into my schema.graphql i've added this fiels...

```
type Pill
  @model{
  id: ID!
  title: String
  images: [S3Object]
}
```

I've find CreatePillInput object into amplify/backend/api/APPNAME/build/schema.graphql and here the field is missing.

input CreatePillInput {
  id: ID
  title: String
  }

Why????

**Comment by MrHertal** [comment]
Hi @mgiorgi-github,

Looks like something is wrong in your schema, did you also add the S3Object type in your schema:

```
type S3Object {
  bucket: String!
  region: String!
  key: String!
}
```

and sorry I have to ask... did you `amplify push`?

**Comment by mgiorgi-github** [comment]
Hi, i've added the S3Object... i've delete and create a new project and it work fine.
