### ISSUE TITLE
AmplifyImageField in list view does not fetch images.

### ISSUE THREAD

**Issue by umepon0626** [MrHertal/react-admin-amplify#42]
I use `AmplifyImageField` in a `<List>` component.
However, it does not fetch images in list view.
After going to show or edit page and getting back to list page, the only row I went to, shows images but the others does not show.

How should I resolve this problem? Thank you!

**Comment by umepon0626** [comment]
According to React dev-tools, the list component does not render an ImageField component.

**Comment by umepon0626** [comment]
So sorry, I checked queries and I found that getList query does not return S3Objects...

**Comment by MrHertal** [comment]
Glad I could help 😊
