### ISSUE TITLE
Enable buildAuthProvider to use Cognito user groups for external providers

### ISSUE THREAD

**Issue by ChloeBellm** [MrHertal/react-admin-amplify#44]
We're using Cognito with Open ID Connect provider with Azure AD for authentication with our company email address. We therefore have an auto generated user group and it would be great if this could be used in the build auth provider function.

Is this possible currently, and if not do you have an idea of how it could be done (we'd be happy to contribute!).

Thanks!

**Comment by MrHertal** [comment]
Hi @ChloeConnor 

The [AuthProvider](https://github.com/MrHertal/react-admin-amplify/blob/master/src/providers/AuthProvider.ts) is retrieving user groups like this:

```
import { Auth } from "@aws-amplify/auth";

const session = await Auth.currentSession();
const groups = session.getAccessToken().decodePayload()["cognito:groups"];
```

You should try this code and see if you can see the user groups or not.
If you are seing the user groups, then the AuthProvider should work properly.

If not, I think you can build the AuthProvider and override `checkAuth` and `getPermissions` methods.
