### ISSUE TITLE
how to handle with `Refresh Token has expired`?

### ISSUE THREAD

**Issue by umepon0626** [MrHertal/react-admin-amplify#46]
When I ran development server and tried to login, I got this error.
My settings about token expiration date is set to default. (So, refresh token expiration date is 30 days). However It's been shorter than 30 days since I last logged in.

Could anyone show me how to deal with this problem??

Thank you!

**Comment by umepon0626** [comment]
I can login on the production page hosted with S3 and cloudFront but I can't login with same user on the development server(my local pc).

Before I get this error, I delete amplify api(dynamoDB) to change key schema and re-add api with new schema. Maybe this re-add the api cause this error, but I cannot find the solution....

What I tried to solve

- Create new user with Cognito dashboard, change password with aws cli and log in with this new user, but I get the same error....

**Comment by umepon0626** [comment]
I delete the local storage via dev tools in chrome and the error change to `No current User`....

**Comment by umepon0626** [comment]
it's package versioning problem...

**Comment by MrHertal** [comment]
Glad I could help 😊
