### ISSUE TITLE
Help wanted: Login form customisation

### ISSUE THREAD

**Issue by RichieMerchant** [MrHertal/react-admin-amplify#50]
I would like to customise the look of the login page but I can't see it anywhere in the documentation. Would you be able to point me to the correct place or advise on how I can do this. Thanks

**Comment by MrHertal** [comment]
Hi, you can check [this page](https://marmelab.com/react-admin/Authentication.html#customizing-the-login-and-logout-components) in the react-admin documentation.

**Comment by RichieMerchant** [comment]
Hi, thanks for getting back to me. Yes, that did the trick. I wasn't sure that react-admin-amplify used the same react-admin login form.
