### ISSUE TITLE
How to use social login google, with cognito?

### ISSUE THREAD

**Issue by danjesus** [MrHertal/react-admin-amplify#63]
Hi,

How can I configure react-admin-amplify to use a social auth provider, which I configured in amplify?

I tried to create a custom authProvider, but even passing the methods it doesn't authenticate, and it keeps returning "no user".

Example: https://gist.github.com/danjesus/6da3efcb7aa50a1443283c701731de2f

Has anyone ever needed to configure react-admin like this?

Some tip?

**Comment by danjesus** [comment]
@MrHertal could you help me?

**Comment by danjesus** [comment]
It just customize login screen, i just created a custom component.

**Comment by saikarthikp9** [comment]
@danjesus Could I see what you ended up doing?
