### ISSUE TITLE
Is this package compatible with React-admin ^4.0.0?

### ISSUE THREAD

**Issue by saikarthikp9** [MrHertal/react-admin-amplify#68]
Would love to use react-admin 4.0.1. I anticipate breaking changes. Was wondering if anyone tried this.

**Comment by saikarthikp9** [comment]
Seems like AmplifyFilter is broken. 
![Screen Shot 2022-04-19 at 2 08 14 AM](https://user-images.githubusercontent.com/69390532/163945892-f7aecb20-6c1e-4ad6-a9f4-abf6550ed887.png)

**Comment by sullix** [comment]
Hi! I have the same thing with react-admin v4.

**Comment by MrHertal** [comment]
Hi, I will work on this soon

**Comment by MrHertal** [comment]
It is now compatible :)

https://github.com/MrHertal/react-admin-amplify/releases/tag/v2.0.0

**Comment by weisisheng** [comment]
Thank you!
